### ISSUE TITLE
error

### ISSUE THREAD

**Issue by taohuadaohongye** [bret99/telegram_scan#1]
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
i do :pip install TgCrypto
but 
when i enter:python telegram_scan.py
its show 
Traceback (most recent call last):
  File "telegram_scan.py", line 3, in <module>
    from get_user_info import User_info
  File "/root/osint/telegram/tgscan/get_user_info.py", line 7, in <module>
    app = Client(session_name='my.session', api_id=access_creds.api_id, api_hash=access_creds.api_hash)
TypeError: __init__() got an unexpected keyword argument 'session_name'

**Comment by taohuadaohongye** [comment]
i know 
pyrogram version must before 1.2.5
if the version is v2
it will error

**Comment by bret99** [comment]
@taohuadaohongye Not cool idea to run this one from root. There is no any malware code but be careful with other software. Have a nice day!
P.S. One should install python3-pip and use "pip3 install ..."
